// Generated by FlutterFire CLI — replace the placeholder values below with
// your real Firebase project credentials before building for Android or iOS.
//
// Steps:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Register an Android app (package: com.vocechat.vocechat_client)
//      and an iOS app (bundle ID from your Xcode project).
//   3. Run:  dart pub global activate flutterfire_cli
//            flutterfire configure
//      That will overwrite this file with real values automatically.
//
// Until you do that, running on Android/iOS will throw at Firebase.initializeApp().

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: replace with values from your google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  // TODO: replace with values from your GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );
}
