"""Android release registry. Run behind an HTTPS reverse proxy; no dependencies."""

import hmac
import json
import os
import secrets
import tomllib
from importlib.resources import files
from pathlib import Path
import re
import sqlite3
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlsplit


MAX_BODY = 64 * 1024


def validate_release(value):
    if not isinstance(value, dict):
        raise ValueError("Expected a JSON object")
    if "timestamp" in value or "last_force_version_code" in value:
        raise ValueError("timestamp and last_force_version_code are generated by the server")
    version = value.get("version")
    if not isinstance(version, str) or not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.+-]+)?", version):
        raise ValueError("version must be a version name such as 0.3.23")
    code = value.get("version_code")
    if type(code) is not int or not 1 <= code <= 2100000000:
        raise ValueError("version_code must be an integer from 1 to 2100000000")
    if type(value.get("force_update")) is not bool:
        raise ValueError("force_update must be a boolean")
    url = value.get("update_url")
    if not isinstance(url, str) or any(c.isspace() or ord(c) < 32 for c in url):
        raise ValueError("update_url must be an HTTPS URL")
    parsed = urlsplit(url)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username is not None:
        raise ValueError("update_url must be an HTTPS URL without credentials")
    _ = parsed.port  # Reject malformed ports before publication.
    announcement = value.get("announcement")
    if announcement is not None and not isinstance(announcement, str):
        if (not isinstance(announcement, dict)
                or not all(isinstance(announcement.get(lang), str) for lang in ("zh", "en"))
                or not all(isinstance(text, str) for text in announcement.values())):
            raise ValueError("announcement must contain zh and en strings")
    # Unknown JSON fields are retained and returned to future clients.
    json.dumps(value, allow_nan=False)
    return value


class ReleaseStore:
    def __init__(self, path):
        self.path = str(path)
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with sqlite3.connect(self.path) as db:
            db.execute("CREATE TABLE IF NOT EXISTS releases "
                       "(version_code INTEGER PRIMARY KEY, payload TEXT NOT NULL, "
                       "last_force_version_code INTEGER NOT NULL DEFAULT 0)")
            # Upgrade existing registries and recover their complete forced
            # release history, including a forced release followed by optional ones.
            db.execute("BEGIN IMMEDIATE")
            columns = {row[1] for row in db.execute("PRAGMA table_info(releases)")}
            if "last_force_version_code" not in columns:
                db.execute("ALTER TABLE releases ADD COLUMN "
                           "last_force_version_code INTEGER NOT NULL DEFAULT 0")
                floor = 0
                for code, payload in db.execute(
                        "SELECT version_code, payload FROM releases ORDER BY version_code").fetchall():
                    if json.loads(payload).get("force_update") is True:
                        floor = code
                    db.execute("UPDATE releases SET last_force_version_code = ? WHERE version_code = ?",
                               (floor, code))

    @staticmethod
    def _metadata(row):
        return {**json.loads(row[0]), "last_force_version_code": row[1]} if row else None

    def latest(self):
        with sqlite3.connect(self.path) as db:
            row = db.execute("SELECT payload, last_force_version_code FROM releases "
                             "ORDER BY version_code DESC LIMIT 1").fetchone()
        return self._metadata(row)

    def get(self, version_code):
        with sqlite3.connect(self.path) as db:
            row = db.execute("SELECT payload, last_force_version_code FROM releases "
                             "WHERE version_code = ?", (version_code,)).fetchone()
        return self._metadata(row)

    def publish(self, release):
        release = validate_release(release)
        payload = json.dumps(release, sort_keys=True, ensure_ascii=True, allow_nan=False)
        with sqlite3.connect(self.path, timeout=10) as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT version_code, payload, last_force_version_code FROM releases "
                             "ORDER BY version_code DESC LIMIT 1").fetchone()
            if row:
                if release["version_code"] == row[0] and payload == row[1]:
                    return False
                if release["version_code"] <= row[0]:
                    raise FileExistsError("Publish a higher version_code; existing releases are immutable")
            floor = release["version_code"] if release["force_update"] else row[2] if row else 0
            db.execute("INSERT INTO releases (version_code, payload, last_force_version_code) VALUES (?, ?, ?)",
                       (release["version_code"], payload, floor))
        return True


class UpdateServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, address, store, admin_token):
        if len(admin_token) < 32 or not admin_token.isascii() or any(c.isspace() for c in admin_token):
            raise ValueError("UPDATE_ADMIN_TOKEN must be at least 32 non-whitespace ASCII characters")
        self.store = store
        self.admin_token = admin_token
        super().__init__(address, Handler)


class Handler(BaseHTTPRequestHandler):
    server_version = "VoceUpdate/1"

    def setup(self):
        super().setup()
        self.connection.settimeout(15)

    def respond(self, status, value):
        body = json.dumps(value, ensure_ascii=True, allow_nan=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def error(self, status, code, message):
        self.respond(status, {"error": {"code": code, "message": message},
                              "timestamp": time.time_ns() // 1_000_000})

    def do_GET(self):
        path = urlsplit(self.path).path
        assets = {
            "/": ("index.html", "text/html; charset=utf-8"),
            "/admin": ("index.html", "text/html; charset=utf-8"),
            "/admin/": ("index.html", "text/html; charset=utf-8"),
            "/admin/app.css": ("app.css", "text/css; charset=utf-8"),
            "/admin/app.js": ("app.js", "text/javascript; charset=utf-8"),
        }
        if path in assets:
            name, content_type = assets[path]
            body = files("vocechat_update").joinpath("static", name).read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", content_type)
            self.send_header("Cache-Control", "no-store")
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("Content-Security-Policy", "default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        if urlsplit(self.path).path != "/client/android":
            self.error(404, "not_found", "Unknown endpoint")
            return
        try:
            release = self.server.store.latest()
        except sqlite3.Error:
            self.error(503, "storage_unavailable", "Release storage is unavailable")
            return
        if release is None:
            self.error(503, "no_release", "No Android release has been published")
            return
        self.respond(200, {**release, "timestamp": time.time_ns() // 1_000_000})

    def do_POST(self):
        if urlsplit(self.path).path != "/admin/client/android/releases":
            self.error(404, "not_found", "Unknown endpoint")
            return
        expected = f"Bearer {self.server.admin_token}".encode("ascii")
        supplied = self.headers.get("Authorization", "").encode("utf-8")
        if not hmac.compare_digest(supplied, expected):
            self.error(401, "unauthorized", "Invalid administrator token")
            return
        if self.headers.get_content_type() != "application/json":
            self.error(415, "unsupported_media_type", "Use application/json")
            return
        if self.headers.get("Transfer-Encoding") is not None:
            self.error(400, "invalid_body", "Use Content-Length, not chunked encoding")
            return
        try:
            size = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            size = 0
        if size <= 0 or size > MAX_BODY:
            self.error(413 if size > MAX_BODY else 400, "invalid_body", "JSON body must be 1–65536 bytes")
            return
        try:
            raw = self.rfile.read(size)
            if len(raw) != size:
                raise ValueError("Incomplete request body")
            release = validate_release(json.loads(raw))
            created = self.server.store.publish(release)
            published = self.server.store.get(release["version_code"])
        except (ValueError, UnicodeError, RecursionError):
            self.error(400, "invalid_release", "Invalid release metadata; check required fields and types")
            return
        except FileExistsError as error:
            self.error(409, "version_conflict", str(error))
            return
        except sqlite3.Error:
            self.error(503, "storage_unavailable", "Release storage is unavailable")
            return
        self.respond(201 if created else 200,
                     {**published, "timestamp": time.time_ns() // 1_000_000})


def load_admin_token(data_dir):
    configured = os.environ.get("UPDATE_ADMIN_TOKEN")
    if configured:
        return configured
    token_path = Path(data_dir) / "admin-token.txt"
    token_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        fd = os.open(token_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        return token_path.read_text(encoding="utf-8").strip()
    with os.fdopen(fd, "w", encoding="utf-8") as output:
        token = secrets.token_urlsafe(48)
        output.write(token + "\n")
    print(f"Administrator token generated in {token_path.resolve()}", flush=True)
    return token


def main():
    config_path = Path("config.toml")
    config = tomllib.loads(config_path.read_text(encoding="utf-8")) if config_path.exists() else {}
    database = os.environ.get("UPDATE_DB", config.get("database", "./data/releases.sqlite3"))
    token = load_admin_token(Path(database).parent)
    store = ReleaseStore(database)
    address = (os.environ.get("UPDATE_HOST", config.get("host", "0.0.0.0")),
               int(os.environ.get("UPDATE_PORT", config.get("port", 8080))))
    server = UpdateServer(address, store, token)
    print(f"Android update service listening on {address[0]}:{address[1]}", flush=True)
    print(f"Release console: http://127.0.0.1:{server.server_port}/admin/", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
